replicaCount: 1
image:
  repository: localhost:32000/service-db-rest-python-v4
  tag: 0.0.1
  pullPolicy: IfNotPresent
env:
- name: SERVICE_VERSION
  value: 0.0.1
- name: SECRET_PROVIDER_ENABLED
  value: 'false'
- name: SECRET_DIRECTORY_PATH
  value: /mnt/secrets-store
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
service:
  enabled: true
  type: ClusterIP
  port: 5000
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilization: 50Mi
pdb:
  enabled: true
  minAvailable: 1
probes:
  livenessProbe:
    enabled: true
    path: /service-db-rest-python-v4/health/liveness
    port: 5000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    path: /service-db-rest-python-v4/health/readiness
    port: 5000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: false
securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
initcontainer:
  enabled: false
nodeSelector:
  enabled: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
  - path: /service-db-rest-python-v4/api/v3/store/inventory
    pathType: Exact
    port: 5000
  - path: /service-db-rest-python-v4/api/v3/store/order
    pathType: Exact
    port: 5000
  - path: /service-db-rest-python-v4/api/v3/store/order/
    pathType: Prefix
    port: 5000
pvc:
  enabled: false
secretProviderClass:
  enabled: false
logs:
  enabled: false
